### ISSUE TITLE
Application with Supervision tree - can you make it useful with mix apps ?

### ISSUE THREAD

**Issue by 0freeman00** [suvash/hulaaki#10]
hello , i want to use hulaaki as mqtt client in my project. but i think it is not according to the mix rules. can you provide that support ?

**Comment by suvash** [comment]
Hi VJ,

I'm not exactly sure what you mean by 'not according to mix rules'. Can you explain a bit more on that ?

Maybe you can explain your problem a bit more, so I can understand what is it that you're actually thinking about.

**Comment by VJOfficial** [comment]
hello , i am using mysql driver, and i don't need to manage connection and supervise process and all. so can hulaaki be something like this ?? automatic process supervision when put it in mix.exs file.

**Comment by suvash** [comment]
Ah, I see. That part (of making an own application with supervision tree) hasn't been worked on yet. Something to be done in the future.

**Comment by miwee** [comment]
for implementation purpose, one flow is following:

- have broker details part of confix.exs similar to Ecto handles its database settings
- need to have a file similar to repo.ex (for Ecto), which will primarily configure the otp_app for Hulaaki.Client (e.g. MyMqtt.Hulaaki) and callback Module for subscribe functions (e.g. MyMqtt.Hulaaki.SubHandle)
- Multiple mqtt_clients can be handled in a single app, by specifying the above 2 details multiple times
- the api for publish will be something like MyMqtt.Hulaaki.publish(topic, message, options)
- the api for subscription will be something like MyMqtt.Hulaaki.subscribe(topic, options) and MyMqtt.Hulaaki.unsubscribe(topic)
-the callback for subscribe will be implemented inside function named sub_callback(topic, message) in the module MyMqtt.Hulaaki.SubHandle 
- the api can be extended to handle other mqtt states like connect/disconnect etc. But to start with the publish and subscribe options should be sufficient.

Waiting for more input on the flow and api structure.

**Comment by suvash** [comment]
@miwee do you have some example (in other projects possibly) you could point to regarding the implementation you had in mind ?

**Comment by miwee** [comment]
I was trying for simplicity of https://pypi.python.org/pypi/paho-mqtt
for erlang reference, I followed https://github.com/emqtt/emqttc. It requires less code than hulaaki to configure and use the client, but still requires GenServer
for hiding GenServer level details, I referred to https://github.com/elixir-ecto/ecto

**Comment by alex88** [comment]
Same here, I was trying to create a genserver that uses your genserver but I have to change the start_link so that when the main genserver starts it also starts the connection based on application parameters

**Comment by i-m-v-j** [comment]
Try new lib.  github.com/i-m-v-j/Bus

**Comment by alex88** [comment]
Oh great, thanks @i-m-v-j

**Comment by i-m-v-j** [comment]
its pleasure. let me know if find any issue. and please share and star it.

**Comment by suvash** [comment]
Closing this for now. For the time being, this library won't provide "easy" integration with Supervision tree, hence not "getting in the way" for various integration. If needed, we can take a look at this again in the future.
