### ISSUE TITLE
how to perform TLS PSK connect?

### ISSUE THREAD

**Issue by yeongsheng-tan** [suvash/hulaaki#14]

**Comment by suvash** [comment]
@yeongsheng-tan Sadly, I haven't had the time to add support for it yet. Maybe sometime this fall.

**Comment by yeongsheng-tan** [comment]
@suvash Sweet. 👍 

ruby-mqtt has this feature lacking and so does the java lib. Seems like you have to roll your own in ruby and java land.

Was hoping you could provide need support similar to the mosquitto_sub and mosquitto_pub utility written in C coming from mosquitto client and broker tooling binary distribution.

**Comment by shymega** [comment]
@suvash I can have a look at TLS, but were you thinking of using Erlang for that?

**Comment by suvash** [comment]
@shymega Not sure what you mean. I'd prefer not using an extra library as a dependency. Built in Erlang interop should be fine. Do let me know what you find.

**Comment by suvash** [comment]
@yeongsheng-tan @shymega TLS/SSL support is added in #27 and has landed in master. Documentation updates coming soon.
