### ISSUE TITLE
Please write changes with new release.

### ISSUE THREAD

**Issue by VJ-OK** [suvash/hulaaki#15]
Hello , if you can write improvements and changes with each release then it would have been really great. please do , if possible.

**Comment by suvash** [comment]
@VJ-OK There's a [changelog](https://github.com/suvash/hulaaki/blob/dfa80b0278c21de59220eaad5ec993deb150b500/CHANGELOG.md) included in the repo. I'll make sure there's a link to it on the Readme as well.
