### ISSUE TITLE
Message Id should be handled internally by driver.

### ISSUE THREAD

**Issue by 0freeman00** [suvash/hulaaki#16]
Hello , as per now , user is entering user id when sending publish message or any other message that requires id, i think it should be handled by driver internally , so user should not worry about it. otherwise in many cases end user might not know that id should be 16 bit long that might create lot of confusion.

**Comment by miwee** [comment]
for implementation purpose, we need a GenServer process to store publish packet_id. We can keep a map, where key is topic and value is packet_id. the options are, Hulaaki.Client or Hulaaki.Connection, as they are both GenServer processes. Or else we can start an Agent for storing this info. If some of these options are decided upon, I can try a PR for this.

**Comment by suvash** [comment]
This is an issue that I'd run into early on during the design and decided to ignore it, making the ids the library user's responsibility.
But maybe it's time to rethink this and come up with a good design where it can be managed by the library, but not completely opaque from the user either.

**Comment by suvash** [comment]
Fixed in #26 and landed on master now.
