### ISSUE TITLE
Docker problem while running tests

### ISSUE THREAD

**Issue by raventid** [suvash/hulaaki#19]
Hi! Thank you very much for this nice project. I've been playing with it for a while and could not run it unfortunately due to my nooby mqtt knoledge

I've tried to run test to better understand how code works and what it does, but after a few hours of tweaking Makefile I finished with this:

```
docker run --rm -it -e MQTT_HOST=hulaaki_mqtt -e MQTT_PORT=1883 --link mosquitto:hulaaki_mqtt  -v /home/julian/elixir_experiments/hulaaki:/usr/src/app hulaaki/dev mix test
** (CaseClauseError) no case clause matching: {:error, :tokens}
    (kernel) file.erl:1368: :file.consult_stream/3
    (kernel) file.erl:978: :file.consult/1
    (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
    (mix) lib/mix/dep.ex:290: Mix.Dep.check_manifest/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (mix) lib/mix/tasks/deps.check.ex:26: Mix.Tasks.Deps.Check.run/1
    (mix) lib/mix/tasks/loadpaths.ex:53: Mix.Tasks.Loadpaths.load_deps/2

Makefile:50: recipe for target 'run' failed
make: *** [run] Error 1
```
Did you try to run this on Ubuntu 16.04 (I'm trying), and is it supposed to work from scratch or I should load some additional stuff?

**Comment by suvash** [comment]
I should've probable made this clear in the Readme.

**Comment by suvash** [comment]
If you already have an elixir runtime and a mqtt broker running on your machine, you should be able to run `mix test` as you would on any other mix projects.
Docker is used for loading all the dependencies(language, broker etc.). I should probably make this more clear in the Readme. Will add some more docs on how to contribute/run tests and close this issue. As long as you have a recent version of docker, nothing else should be required to run/test this project.

**Comment by suvash** [comment]
@raventid the Readme should be helpful enough now.

**Comment by raventid** [comment]
@suvash Ahhhh, I see now, I made a mistake, thx for updated readme very much!
