### ISSUE TITLE
publish messages with qos = 0 have no message id

### ISSUE THREAD

**Issue by ianrumford** [suvash/hulaaki#3]
Hi Suvash.

Thanks very much for writing Hulaaki, its taught me a lot about MQTT.

I'm new to Elixir/Erlang/OTP and Hulaaki has also taught me a lot about
Elixir in general and how to write GenServers. Great stuff!

To understand the MQTT protocol, I been writing some interworking
tests between Hulaaki and the Eclipse Paho Java Client (via a Clojure
wrapper called 'machine-head') and saw a problem with publish messages.

Hulaaki adds a message id to a publish message even when the qos = 0. 
I checked the MQTT spec and Hulaaki should not include and expect a
message id when qos = 0.

I've made some changes in my fork and fixed this. Happy to
supply a pull request (I will need to tidy it up a bit first though).

Regards

**Comment by suvash** [comment]
Oh hi ! Seems like I missed these issues you've opened. Thanks for opening them. :beers: 
Feel free to send a PR if you have something working.

I'll take a look at these.

**Comment by suvash** [comment]
[ MQTT-2.3.1-5 ]

**Comment by ianrumford** [comment]
Hi Suvash,

I've submitted a PR for this one.

**Comment by suvash** [comment]
Thanks a lot @ianrumford . As I've mentioned in your PR, I have taken good bits from your PR and added some necessary bits for the correct implementation. There's a PR open at #6 . Let me know if that solves the issue. In that case I'll go ahead and release the library on hex.  @engwan @miwee

**Comment by ianrumford** [comment]
Hi Suvash,

Just commented in the PR about tests failing.  I have just check and they all passed for me.

**Comment by suvash** [comment]
Merged the PR #6 which implements this. Feel free to use it directly from Github. Will release a version later when other issues are addressed.
