### ISSUE TITLE
List of existing topics

### ISSUE THREAD

**Issue by tomazbracic** [suvash/hulaaki#30]
Hi, 

is there a way to get a list of topics from withing the broker? 

Best,
T

**Comment by suvash** [comment]
@tomazbracic Getting a list of existing topics is not an operation specified in the MQTT spec. (as far as I can tell). You are supposed to know beforehand (keep track of) what topics you plan to subscribe to.

However, you might benefit from checking out the `Topic Names and Topic Filters` section in the MQTT spec. Most brokers should've implemented accordingly. http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718106

Closing this issue, as this library will never support getting a list of topics from the broker. It's going to only provide features specified in the spec. 🍻
