### ISSUE TITLE
Passing SSL cert

### ISSUE THREAD

**Issue by emjrdev** [suvash/hulaaki#36]
This feels like an exceedingly dumb question, but I can't seem to find any way to configure the client's SSL behavior outside of setting the `ssl: true` connection option. I need to send a cert in order to connect to our broker, but can't figure out how. Any help at all would be massively appreciated.

**Comment by suvash** [comment]
The options for ssl are set in `connection.ex`, but none of them except the flag you've mentioned is exposed as of now. As of now, there's no plans to support starting connections with custom certs, as it starts to make the library more complicated. Sorry about this.
An easier way would be to use a properly signed cert on your broker, for eg. using Let's Encrypt etc.

**Comment by emjrdev** [comment]
No need for apologies, thank you very much for your work on the library and prompt reply.
