### ISSUE TITLE
publish messages received with q > 0 must be puback-ed

### ISSUE THREAD

**Issue by ianrumford** [suvash/hulaaki#4]
Hi Suvash,

Bumped into another issue which may be familiar to you.

When Hulaaki subscribes to a topic and receives a publish message with
qos > 0, it must respond with a puback.

You actually left a comment / question in the code of client.ex about this.

I've fixed the issue is my fork - your code is so well structured it was
very easy for me to follow and implement the necessary changes.

Again happy to supply a pull request.

Regards

**Comment by suvash** [comment]
will take a look at this as well.

**Comment by suvash** [comment]
oh please, i'd like a pull request.

**Comment by engwan** [comment]
@ianrumford I checked your fork and you don't have any commits pushed there.

I'm also looking to solve this problem but since you've already fixed it, sharing it with a pull request would be awesome :)

**Comment by ianrumford** [comment]
Hi,

Yes changes are only in repo on my home system; need to tidy up and push to my github repo and generate the PRs.

Do you want a PR for each issue / change or just one?

Planning to do the tidy, etc this weekend.

**Comment by suvash** [comment]
Hi there @ianrumford,

I'd prefer a different PR for each issue. That way it's easier to review/edit/rollback later if needed. Also, would be superb if you could add/update a test for the change.

I've tried to purposely stay away from implementing any qos related conditionals so far. I'd like to come up with a nice design to do so throughout the codebase. Will do some more work on that after I get your PR. :beers:

**Comment by suvash** [comment]
This has just landed in the master (only for qos 1 for the time being) as a merge from #7

**Comment by suvash** [comment]
@ianrumford @engwan Both the issues are taken care of and a new release (0.0.2) is out. :)
