### ISSUE TITLE
Timeouts in regions with poor connectivity

### ISSUE THREAD

**Issue by chintan-mishra** [suvash/hulaaki#40]
As mentioned in the closing remarks of issue https://github.com/suvash/hulaaki/issues/39 the timeouts are being experienced if the application takes more than 5 seconds to publish the data. This issue is experienced in poor connectivity regions as well as if the data packet is large.

**One can reproduce this issue by doing either of the following:**
1. Find your peak internet connection speed, say 5Mbps. Keep your data packet size >= 3.5 MB or so.
2. Throttle your internet speed to the desired value. Keep your data packet size > = 5 * (digits from internet speed). If you have throttled the internet to 15kBps then keep your packet size >= 15 * 5kB = 75kB
While deciding on packet size keep in mind that MQTT permits maximum data packet size of approximately 256MB.

**One can try resolving this by** setting the GenServer timeout to a desired value in [connection.ex](https://github.com/suvash/hulaaki/blob/master/lib/hulaaki/connection.ex#L30) and [client.ex](https://github.com/suvash/hulaaki/blob/master/lib/hulaaki/client.ex#L25).

However, this is a sub-optimal solution for a library. A better solution would be to keep GenServer timeouts equal to timeout defined by the user while connecting with the MQTT client. GenServer timeout for `client.ex` should be greater than that for `connection.ex`.

IMO, a one-second gap would suffice even for systems that are being used heavily.

**Alternate solution:** Having asynchronous `GenServer.cast` for network related calls as they are unreliable and time-invariant.

_**Which path is preferred by the maintainers?**_

I will try to open a Merge Request by mid-April 2018

kB = Kilobytes, Mb = Megabits, MB = Megabytes, ps = per second

**Comment by suvash** [comment]
Thanks for filing this issue. 👏  Can I ask if you're planning/using this on production infra ? In that case, will be looking forward to see your results. In the meantime, I'll try to think of an automated procedure to replicate this environment.

**Comment by chintan-mishra** [comment]
Yes, we will put our application using Hulaaki in production somewhere in the middle of this month. Our production environment is currently closed-beta. But soon we will put our application in open-beta phase.

What results would you be interested in? I will try to arrange metrics for them.

Follow-up question:- Do you plan on supporting QoS 2?

**Comment by suvash** [comment]
> Yes, we will put our application using Hulaaki in production somewhere in the middle of this month. Our production environment is currently closed-beta. But soon we will put our application in open-beta phase.

That sounds great. Good luck with opening it up soon.

> What results would you be interested in? I will try to arrange metrics for them.

Not so much right now. Maybe I can ping you after the platform is open and gets some use.

> Follow-up question:- Do you plan on supporting QoS 2?

Yeah, it is something I've considered to support. But, I really don't have a timeline for it. Might also change the library design a bit. Will require some more 'hammock time' and digging into specs again(which I haven't done in a while).

> For automation of this test: Subscribe to a topic then publish a data packet........

Thanks for the heads up.

**Comment by suvash** [comment]
Hi again. I'm closing this issue as of now. If this continues to be of recurring issue, feel free to open it up again later.
