### ISSUE TITLE
How to specify ca, cert and key for ssl

### ISSUE THREAD

**Issue by yugandharc9** [suvash/hulaaki#50]
Hi I am looking for example in which we can specify ca,cert and key for client validation. Can you please help

**Comment by suvash** [comment]
Hi, as long as you configure your mqtt server with the certs, the ssl: true option should take care of ssl based communication (using the underlying erlang implementation)
If you want to see an example, you can dig in the ssl tests included in this project.

Self-signed certs here:
https://github.com/suvash/hulaaki/tree/master/mosquitto/certs
Mounted/Ports exposed for testing:
https://github.com/suvash/hulaaki/blob/master/docker-compose.yml#L4-L12
Loaded into the mqtt server here:
https://github.com/suvash/hulaaki/blob/master/mosquitto/mosquitto.conf#L277
https://github.com/suvash/hulaaki/blob/master/mosquitto/mosquitto.conf#L335-L342

Configured in the test helper:
https://github.com/suvash/hulaaki/blob/master/test/test_helper.exs#L13-L16
And, finally used in the tests:
https://github.com/suvash/hulaaki/blob/master/test/hulaaki/connection_ssl_test.exs

That's the entirety of it, and should get you going further.
